import type { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Fresh Milk',
    price: 3.50,
    cost: 2.00,
    image: 'https://placehold.co/100x100.png',
    category: 'Dairy',
    stock: 100,
  },
  {
    id: 2,
    name: 'Whole Wheat Bread',
    price: 2.75,
    cost: 1.50,
    image: 'https://placehold.co/100x100.png',
    category: 'Bakery',
    stock: 80,
  },
  {
    id: 3,
    name: 'Free-Range Eggs (12ct)',
    price: 4.25,
    cost: 2.50,
    image: 'https://placehold.co/100x100.png',
    category: 'Dairy',
    stock: 120,
  },
  {
    id: 4,
    name: 'Organic Apples (1lb)',
    price: 3.99,
    cost: 2.20,
    image: 'https://placehold.co/100x100.png',
    category: 'Produce',
    stock: 150,
  },
  {
    id: 5,
    name: 'Chicken Breast (1lb)',
    price: 5.99,
    cost: 3.50,
    image: 'https://placehold.co/100x100.png',
    category: 'Meat',
    stock: 60,
  },
  {
    id: 6,
    name: 'Cheddar Cheese (8oz)',
    price: 4.50,
    cost: 2.80,
    image: 'https://placehold.co/100x100.png',
    category: 'Dairy',
    stock: 90,
  },
  {
    id: 7,
    name: 'Pasta (16oz)',
    price: 1.50,
    cost: 0.80,
    image: 'https://placehold.co/100x100.png',
    category: 'Pantry',
    stock: 200,
  },
  {
    id: 8,
    name: 'Orange Juice (64oz)',
    price: 3.75,
    cost: 2.10,
    image: 'https://placehold.co/100x100.png',
    category: 'Beverages',
    stock: 75,
  },
   {
    id: 9,
    name: 'Organic Spinach (5oz)',
    price: 3.29,
    cost: 1.90,
    image: 'https://placehold.co/100x100.png',
    category: 'Produce',
    stock: 85,
  },
  {
    id: 10,
    name: 'Ground Beef (1lb)',
    price: 4.79,
    cost: 2.90,
    image: 'https://placehold.co/100x100.png',
    category: 'Meat',
    stock: 55,
  },
  {
    id: 11,
    name: 'Almond Milk (64oz)',
    price: 3.99,
    cost: 2.50,
    image: 'https://placehold.co/100x100.png',
    category: 'Beverages',
    stock: 65,
  },
  {
    id: 12,
    name: 'Bananas (1 bunch)',
    price: 2.49,
    cost: 1.20,
    image: 'https://placehold.co/100x100.png',
    category: 'Produce',
    stock: 180,
  },
];
